title = "KubeMap"
description = "MarkMap for Kubernetes - A visual guide to Kubernetes"
footnote = """
Powered by  <a class=link href=https://kubedaily.io target=_blank rel=noopener>kubedaily</a> | 
Theme <a class=link href=https://kubernetesdaily.github.io/kubemap/ target=_blank rel=noopener>KubeMap</a>
"""
keywords = ["hugo", "latex", "theme", "blog", "texify", "texify2", "texify3", "michael", "neuper"]
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
since = "2023"
toc = true
showWordCount = true
showReadingTime = true
rootFontSize = "100%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true
enableInlineShortcodes = true

[commentEngine]
code = """
<script src="https://giscus.app/client.js"
    data-repo="michaelneuper/hugo-texify3"
    data-repo-id="R_kgDOIjPNaQ"
    data-category="General"
    data-category-id="DIC_kwDOIjPNac4CaklA"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="top"
    data-theme=""
    data-lang="en"
    data-loading="lazy"
    crossorigin="anonymous"
    async>
</script>
"""


[sharingbuttons]
facebook = true
twitter = true
email = true
linkedin = true
reddit = true
whatsapp = true
hackernews = true
telegram = true
